### PR TITLE
Issue #171: Disable FS types should be blacklist, use /proc/modules

### PR DESCRIPTION
**Pull request by whackyhack**
On branch issue_171
	modified:   amazon-level-1-scored-v2-0-0.yaml
	modified:   centos-6-level-1-scored-v2-0-1.yaml
	modified:   centos-7-level-1-scored-v2-0-0.yaml
	modified:   centos-7-level-1-scored-v2-1-0.yaml
	modified:   rhels-6-level-1-scored-v2-0-1.yaml
	modified:   rhels-7-level-1-scored-v2-1-0.yaml
	modified:   rhelw-7-level-1-scored-v2-1-0.yaml

### CODE REVIEW

**Comment by whackyhack** [comment]
The whitelist-blacklist reversal is made manually. (The fact that rhels-6 and centos-6 profiles group whitelist under grep first made it this much more difficult.  I took it to revert that, too so every module would use blacklist first.) Fortunately, only v2 benchmarks have these. (Except rhels-5-level-1-scored-v2-2-0.yaml; this could be an omission in that file.)  Then, just
```
sed -i~ '/disable_mount/,/description/{s?/etc/modprobe.d?/proc/modules?;s/pattern: \(.*\)/pattern: "^\1 "/;/match_output:/d;/grep_args:/d;/- .-r/d;}' [a-u]*-v2-*.yaml
```
Functions are verified only in centos-6-level-1-scored-v2-0-1.yaml and centos-7-level-1-scored-v2-1-0.yaml.

**Comment by mew1033** [comment]
@whackyhack Have you tested these with your changes? Everything looks good, there's just a lot of change. Just wanting to make sure everything still audits.

**Comment by whackyhack** [comment]
@mew1033 I tested centos-6-level-1-scored-v2-0-1.yaml and centos-7-level-1-scored-v2-1-0.yaml.

**Comment by basepi** [comment]
Great changes. Thanks!

**Pull request merged**
