### PR TITLE
Added/updated few test cases For CentOS 7

### PR DESCRIPTION
**Pull request by anuragpaliwal80**
Added/updated few test cases For CentOS 7

### CODE REVIEW

**Comment by mew1033** [comment]
So this is adding the entire 2.1.1 version of the profile. Has it been verified, or is it just a copy of 2.1.0?

**Comment by basepi** [comment]
@anuragpaliwal80 Can you please rebase to resolve these conflicts and make the diff only show what's new? The 2.1.1 was added in #69

**Comment by whackyhack** [comment]
Compared with 2.1.0, this moved a couple checks to misc, and added a couple more checks in misc.  The biggest difference from #69 is caused by the two new modules introduced therein, mount and systemctl.  We probably will need to discuss which approach to take.  I like some aspects of the new modules dedicated to specific subsystems, but breaking symmetry with all other Linux profiles makes cross-platform maintenance harder.  Especially mount does not seem to provide new functionality over /proc/mount (but I like the idea about 'soft' vs 'hard' checks, which can be incorporated in other modules) because Linux's /proc/ file system is very stable and is also the basis for the system call. (One disadvantage of function-specific modules is that they conceal actual check from YAML data, making it more difficult to find bugs.)

**Comment by basepi** [comment]
Good point. Maybe we should standardize on the /proc/mounts for the reasons @whackyhack stated.

**Comment by fossam** [comment]
I agree, I would side with /proc/mounts .

**Comment by anuragpaliwal80** [comment]
I will use /proc/mounts rather than mount and will implement soft and hard inside grep module.

**Pull request merged**
