### PR TITLE
Adding checks for Amazon Linux 2016 and CoreOS in misc.yaml file

### PR DESCRIPTION
**Pull request by anuragpaliwal80**
PLEASE DO NOT MERGE IT FOR NOW.

### CODE REVIEW

**Comment by anuragpaliwal80** [comment]
@basepi Can you please review and let me know if this is correct way to implement checks in misc file ?

**Comment by anuragpaliwal80** [comment]
@basepi We are done for this sprint, please review and merge the changes (if all is ok). FYI... We will be adding more checks in coming sprint and hence will start new PR for the same.

**Comment by basepi** [comment]
@anuragpaliwal80 I wonder if we should move this into the amazon linux CIS profile, rather than having it in its own `misc.yaml`. We should only be targeting amazon linux, not `*`. Can you make that change?

**Comment by anuragpaliwal80** [comment]
Sure. We are right now using misc for Amazon Linux and CoreOS, I will make these changes in top.nova file.

**Comment by basepi** [comment]
This is definitely an improvement. But I still think you're going to end up wanting different misc checks for coreos and amazon linux in the long run. It seems like we may just want to add a `misc` section to the existing yaml files for coreos and amazon linux...

Thoughts?

**Comment by anuragpaliwal80** [comment]
Agree this will be better approach as we will have all cis specific checks in one yaml file as well. :)
Thanks for direction.
Let me make these changes.

**Comment by basepi** [comment]
Perfect, thanks!

**Pull request merged**
